sudo: required

# specify generic language since we're using docker
language: generic

services:
  - docker

before_install:
  # command created by travis encrypt-file
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install/update kubectl in travis
  - gcloud components update kubectl
  # login to google cloud using service-account.json file we create
  - gcloud auth activate-service-account --key-file service-account.json
