apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # allow one node to r/w to PVC
  accessModes:
    - ReadWriteOnce
  # specify that 1GB is needed for storage
  resources:
    requests:
      storage: 1Gi