apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  # use let's encrypt to issue certs
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'dima.goncharov@hotmail.com'
    privateKeySecretRef:
      # used by certmanager, not by us
      name: letsencrypt-prod
    # use http process for cert issuing (not DNS)
    http01: {}
