apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: dgoncharov/multi-server
          ports:
            - containerPort: 5000
          # define environment variables
          # note that all env vars have to be strings
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            # note that a secret was created using the following kubectl command:
            # kubectl create secret generic pgpassword --from-literal PGPASSWORD=<pass>
            - name: PGPASSWORD
              valueFrom: 
                secretKeyRef:
                  # name of the secret
                  name: pgpassword
                  # key from all the key/value pairs stored inside the secret,
                  # note that this does not have to match the env var name
                  key: PGPASSWORD
              
